language: c
sudo: required
install: test -e .travis.opam.sh || wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script:
- bash -ex .travis-opam.sh
env:
  global:
    - PINS="logs-async.dev async-uri.dev fastws.dev:."

  matrix:
    - OCAML_VERSION="4.11" PACKAGE="fastws"
    - OCAML_VERSION="4.11" PACKAGE="fastws-async"
os:
- linux
